/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RitualesRouteImport } from './routes/rituales'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'

const RitualesRoute = RitualesRouteImport.update({
  id: '/rituales',
  path: '/rituales',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/rituales': typeof RitualesRoute
  '/demo/convex': typeof DemoConvexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/rituales': typeof RitualesRoute
  '/demo/convex': typeof DemoConvexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/rituales': typeof RitualesRoute
  '/demo/convex': typeof DemoConvexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/focus' | '/rituales' | '/demo/convex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/focus' | '/rituales' | '/demo/convex'
  id: '__root__' | '/' | '/focus' | '/rituales' | '/demo/convex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusRoute: typeof FocusRoute
  RitualesRoute: typeof RitualesRoute
  DemoConvexRoute: typeof DemoConvexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rituales': {
      id: '/rituales'
      path: '/rituales'
      fullPath: '/rituales'
      preLoaderRoute: typeof RitualesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRoute,
  RitualesRoute: RitualesRoute,
  DemoConvexRoute: DemoConvexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
